name: CI

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: ${{ matrix.ros_distro }} (node ${{ matrix.node_version }})
    if: ${{ github.actor != 'RWT-bot' }}
    runs-on: ubuntu-latest
    container:
      image: ros:${{ matrix.ros_distro }}-ros-core
      options: --cap-add=SYS_ADMIN
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [jazzy]
        node_version: [18, 20]
    env:
      ROS_DISTRO: ${{ matrix.ros_distro }}
    steps:
      - name: Install git in container
        run: |
          apt-get update
          apt-get install -q -y git
      - name: Set git safe directory
        run: |
          git config --global safe.directory '*'
      - uses: actions/checkout@v4
        env:
          TOKEN: "${{ github.event_name == 'push' && endsWith(github.ref, 'develop') && matrix.ros_distro == 'jazzy' && secrets.RWT_BOT_PAT || github.token }}"
        with:
          token: ${{ env.TOKEN }}
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{ matrix.node_version }}
      - name: Own /github/home and PWD
        run: |
          chown -hR 1001:121 /github/home .
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y -q python3-colcon-common-extensions python3-rosdep python3-vcstool && rm -rf /var/lib/apt/lists/*

      - name: Clone rosbridge_suite
        run: |
          git clone --recursive --branch=ros2     https://github.com/RobotWebTools/rosbridge_suite.git src/rosbridge_suite

      - name: Install ROS dependencies
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.bash
          && apt-get update -y
          && rm /etc/ros/rosdep/sources.list.d/20-default.list
          && rosdep init
          && rosdep update
          && rosdep install -i --from-path src --rosdistro ${ROS_DISTRO} -y 
          && colcon build

      - name: Tests
        run: |
          bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && bash test/build.bash"
